[package]
name = "industry-guidelines"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
bitflags = "2.6.0"
serde = { version = "1.0.210", features = ["derive"] }
zerocopy = { version = "0.8.3", features = ["derive"] }

